### ISSUE TITLE
Consider taking in django-geo-spaas-svp-drifters in this app

### ISSUE THREAD

**Issue by mortenwh** [nansencenter/django-geo-spaas-surface-drifters#2]
The svp drifters are also surface drifters. Could you consider merging the repositories to have everything in one place?

**Comment by korvinos** [comment]
@mortenwh No, this is totally not a generic app while the SVP can sustainably stay apart. 

There are unique campaigns when iSphere, CODE, and so on drifters were deployed. So the data are stored without any order/system/standard.  Thus you basically have to write a whole new ingester for every single campaign. It is not efficient at all. Hence, I am trying to anchor all data from different campaigns (3 of those are available at the moment) in one place with probability to DRY it a bit.

SVP Drifters have a certain system and order so I believe that they can stay apart from that.

I maybe should think about changing  a name of the app instead
